# Nixpacks configuration for ChurchTools Facts Exporter

[start]
cmd = "bun run start"

[build]
cmd = "bun install"

[variables]
NODE_ENV = "production"
PORT = "3000"

[setup]
providers = ["bun"]

# Add unzip as a system dependency for bun installation
[phases.setup]
dependsOn = []
aptPkgs = ["unzip"]
