# Nixpacks configuration for ChurchTools Facts Exporter

[start]
cmd = "bun run start"

[build]
cmd = "bun install"

[variables]
NODE_ENV = "production"
PORT = "3000"
NODE_VERSION = "20"

[phases.install]
dependsOn = []
cmds = [
    "curl -fsSL https://bun.sh/install | bash",
    "export PATH=\"$HOME/.bun/bin:$PATH\"",
    "bun install",
]

[phases.build]
dependsOn = ["install"]
cmds = []

[setup]
providers = ["bun"]
